apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k22-optimized
  namespace: windows-perf
  labels:
    app: win2k22-optimized
spec:
  runStrategy: Always
  preference:
    kind: VirtualMachineClusterPreference
    name: windows.2k22.virtio
  dataVolumeTemplates:
    - metadata:
        name: win2k22-optimized-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: win2k22
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 80Gi
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k22-optimized
    spec:
      domain:
        cpu:
          sockets: 2
          cores: 2
          threads: 1
        memory:
          guest: 8Gi
        resources:
          requests:
            memory: 8Gi
            cpu: "4"
        devices:
          blockMultiQueue: true
          networkInterfaceMultiqueue: true
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: win2k22-optimized-rootdisk
