apiVersion: v1
kind: ConfigMap
metadata:
  name: virt-performance-profile
  namespace: clusters
data:
  tuning: |
    apiVersion: performance.openshift.io/v2
    kind: PerformanceProfile
    metadata:
      name: virt-workers
    spec:
      cpu:
        isolated: "4-31"
        reserved: "0-3"
      hugepages:
        defaultHugepagesSize: "1G"
        pages:
        - size: "1G"
          count: 16
      numa:
        topologyPolicy: restricted
      nodeSelector:
        node-role.kubernetes.io/worker: ""
