apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: hardware-inventory
  namespace: hardware-inventory
spec:
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: "$(cat $HOME/.ssh/id_rsa.pub)"
