apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: hcp-demo
  namespace: hcp-virt-demo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: hcp-demo
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 2Gi
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: hcpdemo
            chpasswd:
              expire: false
