apiVersion: v1
kind: Secret
metadata:
  name: vsphere-credentials
  namespace: openshift-mtv
  labels:
    createdForResourceType: providers
    createdForProviderType: vsphere
    createdForResource: vsphere-provider
type: Opaque
stringData:
  user: administrator@vsphere.local
  password: <vcenter_password>
  insecureSkipVerify: "false"
  cacert: |
    -----BEGIN CERTIFICATE-----
    <vcenter_ca_certificate_contents>
    -----END CERTIFICATE-----
